### ISSUE TITLE
Compile problem with Ubuntu/Mint 19

### ISSUE THREAD

**Issue by DavidJRichards** [drmpeg/gr-dvbs#1]
I have not been able to compile the library without editing the modulator constructor. I looked in the similar dvbs2 package and tried an alternative means to initialise the variables, see below: This does compile and appears to run but I have not tried to receive the output yet although the fft plot in the example looks promising. Kind regards, David.

    /*
     * The private constructor
     */
    modulator_bc_impl::modulator_bc_impl()
      : gr::block("modulator_bc",
              gr::io_signature::make(1, 1, sizeof(unsigned char)),
              gr::io_signature::make(1, 1, sizeof(gr_complex)))
    {
//      double r1;
//      double m = 1.0;
//      r1 = m;
	double r1 = 1.0;
        qpsk[0] = gr_complex((r1 * cos(M_PI / 4.0)), (r1 * sin(M_PI / 4.0)));
        qpsk[1] = gr_complex((r1 * cos(7 * M_PI / 4.0)), (r1 * sin(7 * M_PI / 4.0)));
        qpsk[2] = gr_complex((r1 * cos(3 * M_PI / 4.0)), (r1 * sin(3 * M_PI / 4.0)));
        qpsk[3] = gr_complex((r1 * cos(5 * M_PI / 4.0)), (r1 * sin(5 * M_PI / 4.0)));
        qpsk[4] = gr_complex(0.0,0.0);
/*
        qpsk[0].real() = (cos(M_PI / 4.0));
        qpsk[0].imag() = (sin(M_PI / 4.0));
        qpsk[1].real() = (cos(7 * M_PI / 4.0));
        qpsk[1].imag() = (sin(7 * M_PI / 4.0));
        qpsk[2].real() = (cos(3 * M_PI / 4.0));
        qpsk[2].imag() = (sin(3 * M_PI / 4.0));
        qpsk[3].real() = (cos(5 * M_PI / 4.0));
        qpsk[3].imag() = (sin(5 * M_PI / 4.0));
        qpsk[4].real() = 0.0;
        qpsk[4].imag() = 0.0;
*/
        set_output_multiple(2);
    }

**Comment by drmpeg** [comment]
Thanx for pointing this out. I've pushed the fix.
